# Generated by Django 6.1 on 2026-09-03 12:13

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Brand', max_length=200)),
                ('logo', models.URLField(blank=True, null=True, validators=[core.validators.validate_url])),
                ('description', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True, validators=[core.validators.validate_url])),
                ('youtube', models.URLField(blank=True, null=True, validators=[core.validators.validate_url])),
                ('tiktok', models.URLField(blank=True, null=True, validators=[core.validators.validate_url])),
                ('instagram', models.URLField(blank=True, null=True, validators=[core.validators.validate_url])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo_close_up', models.URLField(blank=True, null=True, validators=[core.validators.validate_url])),
                ('photo_selfie', models.URLField(blank=True, null=True, validators=[core.validators.validate_url])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('stage_name', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, null=True, validators=[core.validators.validate_url])),
                ('instagram', models.URLField(blank=True, null=True, validators=[core.validators.validate_url])),
                ('tiktok', models.URLField(blank=True, null=True, validators=[core.validators.validate_url])),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('terdaftar', 'Terdaftar'), ('terverifikasi', 'Terverifikasi')], default='terdaftar', max_length=20)),
                ('song_1', models.CharField(blank=True, max_length=200, null=True)),
                ('song_2', models.CharField(blank=True, max_length=200, null=True)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('verified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
