# Generated by Django 6.1 on 2026-09-02 16:14

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image_preview',
            field=models.URLField(blank=True, null=True, validators=[blog.validators.validate_url]),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='link',
            field=models.URLField(blank=True, null=True, validators=[blog.validators.validate_url]),
        ),
    ]
